;-------------------------------------------------------------------------------------
;MMC5 REGISTER DEFINES

MMC5_PRGMODE          = $5100
MMC5_CHRMODE          = $5101
MMC5_EXRAMPROTECT1    = $5102
MMC5_EXRAMPROTECT2    = $5103
MMC5_EXRAMMODE        = $5104
MMC5_NAMETABLES       = $5105

MMC5_PRG_6000         = $5113
MMC5_PRG_8000         = $5114
MMC5_PRG_A000         = $5115
MMC5_PRG_C000         = $5116
MMC5_PRG_E000         = $5117

MMC5_CHR_0000         = $5120
MMC5_CHR_0400         = $5121
MMC5_CHR_0800         = $5122
MMC5_CHR_0C00         = $5123
MMC5_CHR_1000         = $5124
MMC5_CHR_1400         = $5125
MMC5_CHR_1800         = $5126
MMC5_CHR_1C00         = $5127

MMC5_IRQSCANLINE      = $5203
MMC5_IRQSTATUS        = $5204
